<?php

namespace Systeo\UserBundle\Repository;
use Doctrine\ORM\QueryBuilder;
/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function MyFindAll($data)
   {
       $queryBuilder = $this->createQueryBuilder('a');
       
       //$this->notSuperAdmin($queryBuilder);
       $this->searchName($queryBuilder,$data);
       $this->searchActive($queryBuilder,$data);
       
       $query = $queryBuilder->getQuery();
       $results = $query->getResult();
       
       return $results;
   }
   
   private function notSuperAdmin(QueryBuilder $qb)
   {
       $qb->andWhere('a.id != :value')
              ->setParameter('value', 1);
   }
   
   /**
    * 
    * @param type $name
    */
   private function searchName(QueryBuilder $qb, $data)
   {
       if(isset($data['search']) && !empty($data['search'])){
           $qb->andWhere('a.firstName like :search or '
                   . 'a.lastName like :search or '
                   . 'a.email like :search or '
                   . 'a.username like :search')
              ->setParameter('search', '%'.$data['search'].'%');
       }
   }
   
   private function searchActive(QueryBuilder $qb, $data)
   {
       if(isset($data['active']) && $data['active']!=''){
           $qb->andWhere('a.active = :active')
              ->setParameter('active', $data['active']);
       }
   }
}
