parameters:
    database_host: 127.0.0.1
    database_port: null
    database_name: harice
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    secret: ThisTokenIsNotSoSecretChangeIt
    wkhtmltopdf_commande: wkhtmltopdf
    wkhtmltoimage_commande: wkhtmltoimage
    ckeditor_toolbar_1: [ [ 'Bold', 'Italic', 'Underline', 'Strike'],'-',['Undo','Redo' ] ,'-',['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],'-',['NumberedList','BulletedList','-','Outdent','Indent'],'-',['Link','Unlink'],'-',['Smiley']]
    ckeditor_toolbar_2: [ [ 'Bold', 'Italic', 'Underline', 'Strike'],'-',['Undo','Redo' ] ,'-',['JustifyLeft','JustifyCenter','JustifyRight','JustifyBlock'],'-',['NumberedList','BulletedList','-','Outdent','Indent'],'-',['Link','Unlink'],'-',['Smiley']]

