<?php

namespace Systeo\VenteBundle\Repository;

/**
 * PieceLigneRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PieceLigneRepository extends \Doctrine\ORM\EntityRepository
{
}
