<?php

namespace Systeo\BanqueBundle\Repository;

/**
 * BanqueCompteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BanqueCompteRepository extends \Doctrine\ORM\EntityRepository
{
}
