<?php

namespace Systeo\DepenseBundle\Repository;
use Gedmo\Tree\Traits\Repository\ORM\NestedTreeRepositoryTrait;
use Systeo\DepenseBundle\Entity\DepenseCategory;

/**
 * DepenseCategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DepenseCategoryRepository extends \Doctrine\ORM\EntityRepository
{
    use NestedTreeRepositoryTrait; // or MaterializedPathRepositoryTrait or ClosureTreeRepositoryTrait.

    public function __construct(EntityManager $em, ClassMetadata $class)
    {
        parent::__construct($em, $class);

        $this->initializeTreeRepository($em, $class);
    }
    
    public function getChildrenIds(DepenseCategory $categ){
        
        $queryBuilder = $this->createQueryBuilder('a');
        
         $queryBuilder->where('a.root = :root AND a.lft >= :lft AND rgt <= :rgt')
                      ->setParameter('root', $categ->getRoot())
                      ->setParameter('lft', $categ->getRgt())
                      ->setParameter('rgt', $categ->getLft());
         
         $results = $queryBuilder->getQuery()->execute();
         
         $tab = [];
         
         foreach($results as $rt):
             $tab[] = $rt->getId();
         endforeach;
         
         return $tab;
        
    }
}
